epochs = 22
# hidden = [["relu","80"],["relu","80"]]  # cannot mix types in a TOML array
hidden = [["relu", "80"], ["relu", "80"]]  # [["relu", "80"]]   #[["relu", "80"], ["relu", "80"]]
alpha =  0.05		  # 0.74
reg =  "L2"
maxnorm_lim = [4.0]
lambda =  0.000201  # 0.000191
learn_decay = [0.6,5.0]
mb_size_in =   50
norm_mode = ""
dobatch = true
do_batch_norm =  true
opt =   "adam"
opt_params = [0.9, 0.999]
classify = "softmax"
dropout = false
droplim = [1.0,0.8,1.0]
stats = ["train", "test", "cost", "learning", "epoch"]
plot_now = true
quiet = true
initializer = "xavier"
scale_init = 2.2
bias_initializer = 0.3
