
epochs =  24
n_hid = [80]
alpha =   0.74
reg =  "L2"
maxnorm_lim = [4.0]
lambda =  0.000191
learn_decay = [0.5,4.0]
mb_size_in =   50
norm_mode =   "none"
dobatch = true
do_batch_norm =  true
opt =   "adam"
opt_params = [0.9, 0.999]
units =  "relu"
classify = "softmax"
dropout = false
droplim = [1.0,0.8,1.0]
plots = ["learning", "test", "train"]
plot_now = true
quiet = true
initializer = "xavier"
scale_init = 2.2
bias_initializer = 0.3
shuffle = false