epochs = 25
# hidden = [["relu","80"],["relu","80"]]  # cannot mix types in a TOML array
hidden = [["relu", "1024"], ["relu", "1024"]]  # []   #, ["relu", "200"] [["relu", "80"], ["relu", "80"]]
alpha =  0.12		  # 0.74
reg =  "L2"
maxnorm_lim = [5.5]
lambda =  0.000301  # 0.000191
learn_decay = [0.6,4.0]
mb_size_in =   50
norm_mode = ""
dobatch = true
do_batch_norm =  true
reshuffle = false
opt =   "adam"
opt_output = false
opt_batch_norm = false
opt_params = [0.90, 0.999]
classify = "softmax"
dropout = true
droplim = [0.6]  # hidden, hidden...   nothing for output or input
stats = ["train", "test", "learning", "epoch"]
plot_now = true
quiet = true
initializer = "xavier"
scale_init = 2.2
bias_initializer = 0.0
