
epochs =  16
hidden = [["relu","80"]]  # use text for numbers: cannot mix types in a TOML array
alpha =   0.4
reg =  "L2"
maxnorm_lim = [4.0]
lambda =  0.000191
learn_decay = [0.5,3.0]
mb_size_in =   50
norm_mode =   ""
dobatch = true
do_batch_norm =  true
opt =   "adam"
opt_params = [0.9, 0.999]
classify = "sigmoid"
dropout = false
droplim = [1.0,0.8,1.0]
stats = ["learning", "test", "train"]
plot_now = false
quiet = true
initializer = "xavier"
scale_init = 2.2
bias_initializer = 0.3
